docker:
    image: scdnaprod.azurecr.io/singlecellpipeline/single_cell_pipeline_hmmcopy:v0.8.16
    mounts:
      refdata: /refdata
      datadrive: /datadrive
      mnt: /mnt    
context:
  alljobs:
    name_match: '*destruct*'
    ctx:
      disk: 200
